version: "3.9"

services:
  web:
    build: .
    container_name: go-rest
    ports:
      - "8080:8080"
    networks:
      - default
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
    container_name: postgres
    networks:
      - default

networks:
  default:
    driver: bridge